### ISSUE TITLE
【Backend】画像をアップロードした際のバグを解消する

### ISSUE THREAD

**Issue by mcatm** [mcatm/rippingyard#104]
- 201が返った直後に、再度PUTのリクエストが飛んでいて（同時刻）、そちらがエラー吐いてる
- どうやらJSの方のエラーではなさそうで、`@image.save`が二回走っちゃってるっぽい
- Webrickのエラー？

```
Started PUT "/api/v1/images/upload.json" for 192.168.99.1 at 2016-10-19 01:27:38 +0900
Processing by Api::V1::ImagesController#upload as JSON
 Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x0055f6645e0460 @tempfile=#<Tempfile:/tmp/RackMultipart20161019-1-elbeam.jpg>, @original_filename="bg.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"bg.jpg\"\r\nContent-Type: image/jpeg\r\n">}
Can't verify CSRF token authenticity
#<ActionDispatch::Http::UploadedFile:0x0055f6645e0460 @tempfile=#<Tempfile:/tmp/RackMultipart20161019-1-elbeam.jpg>, @original_filename="bg.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"bg.jpg\"\r\nContent-Type: image/jpeg\r\n">
#<Magick::Image:0x0055f664571970>
  (0.1ms)  begin transaction
 SQL (3.0ms)  INSERT INTO "images" ("name", "type", "path", "mime", "resident_id", "width", "height", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)  [["name", "bg.jpg"], ["type", "image"], ["path", "cca2b0a4803bb2678bb2039bc5f0adfe.jpg"], ["mime", "image/jpeg"], ["resident_id", 1], ["width", 1435], ["height", 1200], ["created_at", "2016-10-18 16:27:38.757462"], ["updated_at", "2016-10-18 16:27:38.757462"]]
  (2.1ms)  commit transaction
 Rendered api/v1/images/upload.json.jbuilder (1.9ms)
Completed 201 Created in 570ms (Views: 38.0ms | ActiveRecord: 5.2ms)


Started PUT "/api/v1/images/upload.json" for 192.168.99.1 at 2016-10-19 01:27:38 +0900
Processing by Api::V1::ImagesController#upload as JSON
 Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x0055f6641445f0 @tempfile=#<Tempfile:/tmp/RackMultipart20161019-1-1efxv0f.jpg>, @original_filename="bg.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"bg.jpg\"\r\nContent-Type: image/jpeg\r\n">}
[2016-10-19 01:27:39] ERROR URI::InvalidURIError: bad URI(is not URI?): http://ry.local:8080/images/#<Image:0x0055f6640ee9e8>
/usr/local/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge'
/usr/local/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
/usr/local/lib/ruby/2.3.0/webrick/httpresponse.rb:277:in `setup_header'
/usr/local/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:16:in `setup_header'
/usr/local/lib/ruby/2.3.0/webrick/httpresponse.rb:207:in `send_response'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:112:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2016-10-19 01:27:40] ERROR URI::InvalidURIError: bad URI(is not URI?): http://ry.local:8080/images/#<Image:0x0055f6639cdf88>
/usr/local/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge'
/usr/local/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
/usr/local/lib/ruby/2.3.0/webrick/httpresponse.rb:277:in `setup_header'
/usr/local/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:16:in `setup_header'
/usr/local/lib/ruby/2.3.0/webrick/httpresponse.rb:207:in `send_response'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:112:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2016-10-19 01:27:40] ERROR URI::InvalidURIError: bad URI(is not URI?): http://ry.local:8080/images/#<Image:0x0055f662364580>
/usr/local/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge'
/usr/local/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
/usr/local/lib/ruby/2.3.0/webrick/httpresponse.rb:277:in `setup_header'
/usr/local/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:16:in `setup_header'
/usr/local/lib/ruby/2.3.0/webrick/httpresponse.rb:207:in `send_response'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:112:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by mcatm** [comment]
WEBrickがエラー吐いてる？？（railsのログには`[2016-10-19 01:27:40] ERROR URI::InvalidURIError: bad URI(is not URI?)`にあたるログは出てこない）

**Comment by mcatm** [comment]
- 画像をアップすると、レスポンスが二回返ってくる
- jpgをアップすると、一回目はjpg、二回目はpngが返ってくる
- pngをアップすると、api/v1/upload.jsonがNot Foundになっている

**Comment by mcatm** [comment]
- http://josephndungu.com/tutorials/ajax-file-upload-with-dropezonejs-and-paperclip-rails

```
Dropzone.autoDiscover = false;
```

**Comment by mcatm** [comment]
取り急ぎ、解消されたのでクローズ。
`respond_to`が悪さしてたっぽい。
